
const constants = {
	ADD_NOTE: "ADD_NOTE",
	EDIT_NOTE: "EDIT_NOTE",
	DELETE_NOTE: "DELETE_NOTE",
	FETCH_NOTES: "FETCH_NOTES",
  CANCEL_FETCHING: "CANCEL_FETCHING",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	NOTE_IN_VIEW: "NOTE_IN_VIEW",
	ACTIONS: {
		ADDING: "ADDING",
		FINISH_ADDING: "FINISH_ADDING",
		VIEWING: "VIEWING",
		FINISH_VIEWING: "FINISH_VIEWING",
		DELETING: "DELETING",
		FINISH_DELETING: "FINISH_DELETING",
		EDITING: "EDITING",
		FINISH_EDITING: "FINISH_EDITING",
	},
	HTTP: {
		DELETE: "DELETE",
		GET: "GET",
		PATCH: "PATCH",
		POST: "POST",
		PUT: "PUT",
		HEADERS: {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    }
	},
  URLS: {
    FLATNOTES_API: 'http://localhost:3000/api/v1/notes'
  }
}

export default constants

